name: delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  http: ^1.4.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.3.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  awesome_dialog: ^3.2.1
  

flutter:
  uses-material-design: true
  assets:
      - assets/svg/
      - assets/png/
      - assets/icons/
      - assets/menus/
      - assets/avatars/
